param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectPath,
    [string]$UnityPath = "C:\Program Files\Unity\Hub\Editor\2021.3.45f2\Editor\Unity.exe",
    [string]$OutputDirectory = (Join-Path $PSScriptRoot "output")
)

$ErrorActionPreference = 'Stop'
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host " [Engine-Build] Starting Android Build" -ForegroundColor Cyan
Write-Host " Project: $ProjectPath" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan

# 1. Locate Unity Editor if default path does not exist
if (!(Test-Path -LiteralPath $UnityPath)) {
    $found = Get-ChildItem "C:\Program Files\Unity\Hub\Editor\*\Editor\Unity.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($found) {
        $UnityPath = $found.FullName
        Write-Host "  -> Unity dynamically detected: $UnityPath" -ForegroundColor Green
    } else {
        throw "Unity.exe not found at: $UnityPath"
    }
}

# 2. Configure log and output directory
$logDir = Join-Path $PSScriptRoot "logs"
New-Item -ItemType Directory -Path $logDir -Force | Out-Null
New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$logFile = Join-Path $logDir "build-$timestamp.log"

Write-Host "  -> Unity Path: $UnityPath" -ForegroundColor DarkGray
Write-Host "  -> Log File: $logFile" -ForegroundColor DarkGray

# 3. Launch Unity in batchmode with real-time monitoring
$arguments = "-batchmode -nographics -quit -projectPath `"$ProjectPath`" -buildTarget Android -executeMethod ProductionBuild.Android -logFile `"$logFile`""
$startTime = Get-Date

Write-Host "`n[1/3] Launching Unity Editor process..." -ForegroundColor Yellow
$process = Start-Process -FilePath $UnityPath -ArgumentList $arguments -WindowStyle Hidden -PassThru

# Monitor log in real time
$lastReadPos = 0
$phasesSeen = @{}

while (!$process.HasExited) {
    Start-Sleep -Seconds 3
    if (Test-Path -LiteralPath $logFile) {
        try {
            $stream = [System.IO.File]::Open($logFile, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
            if ($stream.Length -gt $lastReadPos) {
                $stream.Seek($lastReadPos, [System.IO.SeekOrigin]::Begin) | Out-Null
                $reader = New-Object System.IO.StreamReader($stream)
                $chunk = $reader.ReadToEnd()
                $lastReadPos = $stream.Length
                $reader.Close()
                
                # Identify main build phases
                if ($chunk -match "Scripts has have been compiled" -and !$phasesSeen.ContainsKey("Scripts")) {
                    $phasesSeen["Scripts"] = $true
                    Write-Host "  [*] C# scripts compiled successfully." -ForegroundColor Green
                }
                if ($chunk -match "Compiling shader" -and !$phasesSeen.ContainsKey("Shaders")) {
                    $phasesSeen["Shaders"] = $true
                    Write-Host "  [*] Compiling shaders and graphics variants..." -ForegroundColor Cyan
                }
                if ($chunk -match "Building IL2CPP" -and !$phasesSeen.ContainsKey("IL2CPP")) {
                    $phasesSeen["IL2CPP"] = $true
                    Write-Host "  [*] Running IL2CPP converter for ARM64..." -ForegroundColor Cyan
                }
                if ($chunk -match "Building APK" -and !$phasesSeen.ContainsKey("APK")) {
                    $phasesSeen["APK"] = $true
                    Write-Host "  [*] Packaging final APK via Gradle..." -ForegroundColor Cyan
                }
            }
            $stream.Close()
        } catch { }
    }
}

$duration = [Math]::Round(((Get-Date) - $startTime).TotalMinutes, 1)
Write-Host "`n[2/3] Unity process completed in $duration minutes with exit code: $($process.ExitCode)" -ForegroundColor $(if ($process.ExitCode -eq 0) { "Green" } else { "Red" })

if ($process.ExitCode -ne 0) {
    Write-Host "`n[ERROR] Unity reported build failure. Last 30 log lines:" -ForegroundColor Red
    Get-Content $logFile -Tail 30 | ForEach-Object { Write-Host "  $_" -ForegroundColor DarkRed }
    throw "Android build failed with exit code $($process.ExitCode). Check $logFile"
}

# 4. Locate APK generated by ProductionBuild
$sourceApk = Join-Path (Directory.GetParent($ProjectPath).FullName) "builds\Android\DCGO-android.apk"
if (!(Test-Path -LiteralPath $sourceApk)) {
    $sourceApk = Join-Path $ProjectPath "builds\Android\DCGO-android.apk"
}

if (!(Test-Path -LiteralPath $sourceApk)) {
    throw "APK not found after build. Please check the log: $logFile"
}

# 5. Copy to converter output folder
Write-Host "`n[3/3] Exporting APK to distribution directory..." -ForegroundColor Yellow
$destApkName = "DCGO-android-$timestamp.apk"
$destApkPath = Join-Path $OutputDirectory $destApkName
$latestApkPath = Join-Path $OutputDirectory "DCGO-android-latest.apk"

Copy-Item -LiteralPath $sourceApk -Destination $destApkPath -Force
Copy-Item -LiteralPath $sourceApk -Destination $latestApkPath -Force

$fileInfo = Get-Item -LiteralPath $destApkPath
$hash = (Get-FileHash -LiteralPath $destApkPath -Algorithm SHA256).Hash
$sizeMb = [Math]::Round($fileInfo.Length / 1MB, 2)

Write-Host "==========================================" -ForegroundColor Green
Write-Host " [Engine-Build] Build Completed Successfully!" -ForegroundColor Green
Write-Host " Generated APK: $destApkPath" -ForegroundColor Green
Write-Host " Latest Build Link: $latestApkPath" -ForegroundColor Green
Write-Host " File Size: $sizeMb MB" -ForegroundColor Green
Write-Host " SHA256: $hash" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green

return $latestApkPath