name: Build Unity Android & Enviar Telegram

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: {}

jobs:
  build:
    name: Compilar APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Conversor (Este Repo)
        uses: actions/checkout@v4

      - name: Baixar Jogo Original do GitHub (DCGO2)
        run: git clone https://github.com/DCGO2/DCGO.git UnityProject

      - name: Aplicar Patches de Correção para Android
        shell: pwsh
        run: ./Engine-Patch.ps1 -ProjectPath ./UnityProject

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: UnityProject/Library
          key: Library-Android

      - name: Compilar Jogo Android
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: UnityProject
          targetPlatform: Android
          buildName: DCGO
          buildsPath: build

      - name: Salvar arquivo ALF se não houver licença
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Unity_v2021.3.45f2.alf
          path: ./**/*.alf

      - name: Enviar APK para o Telegram
        uses: appleboy/telegram-action@master
        if: success()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: build/Android/DCGO.apk
          message: "🚀 Nova versão do DCGO compilada nas nuvens do GitHub e pronta para jogar!"
